version: "3.8"
services:
  linuxgsm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ets2server
    restart: unless-stopped
    ports:
      - "27015:16511/tcp"
      - "27016:16206/tcp"
      - "27015:16511/udp"
      - "27016:16206/udp"
