version: "3.8"
services:
  linuxgsm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ets2server
    restart: unless-stopped
#    ports:
#      - "27015:16206/tcp"
#      - "27016:16039/tcp"
#     - "27015:17351/udp"
#      - "27016:1490/udp"
